"""add contacted field to users table

Revision ID: 14858db7bdea
Revises: f8eed70e5263
Create Date: 2024-02-13 11:37:04.463095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14858db7bdea'
down_revision: str = 'f8eed70e5263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contacted', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_users_contacted'), 'users', ['contacted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_contacted'), table_name='users')
    op.drop_column('users', 'contacted')
    # ### end Alembic commands ###
